version: '3.8'

services:
  vault:
    image: hashicorp/vault:1.19.0
    ports:
      - "8300:8300"
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=root
    volumes:
      - vault-data:/vault/file
    cap_add:
      - IPC_LOCK
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    depends_on:
      - vault

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - HTTPS=true
      - SSL_CRT_FILE=/certs/certificate.crt
      - SSL_KEY_FILE=/certs/private.key
    volumes:
      - ./certs:/certs  # Mount the certs folder to the frontend container
    command: >
      sh -c "HTTPS=true SSL_CRT_FILE=/certs/certificate.crt SSL_KEY_FILE=/certs/private.key npm start"
    depends_on:
      - backend
    networks:
      - default

volumes:
  vault-data:

networks:
  default:
    name: vault-net
    external: true
